++++++++++[>++++++++<-]>+++.   # Print 'S'(ASCII value 83)
>+++++++++++[>+++++++++<-]>.   # Print 'c'(ASCII value 99)
>++++++++++[>++++++++++<-]>++++.   # Print 'h' (ASCII value 104)
>++++++++++[>++++++++++<-]>+++++++++++.   # Print 'o' (ASCII value 111)
>++++++++++[>++++++++++<-]>+++++++++++.   # Print 'o' (ASCII value 111)
>++++++++++[>++++++++++<-]>++++++++.   # Print 'l' (ASCII value 108)
>++[>+++++<-]>.   # Print newline '\n'(ASCII value 10)
